### ISSUE TITLE
Replace hardcoded i2c address with configuration variable

### ISSUE THREAD

**Issue by ati** [jfosnight/jonahsystems#1]
Thank you for the MS5611 module. 
I found useful to replace hardcoded i2c address with configuration variable:

https://gist.github.com/ati/569b4507c30c589264c1035f6e9399f5

**Comment by jfosnight** [comment]
Good catch.  I had meant for the code to have that in there, hence why the i2c variable can be passed in on initialization.  I guess I just forgot to actually update the rest of the code to use the variable.
